### PR TITLE
Implements upstream to fix [Bug 2782 - 8-bit FLAC samples are not imported correctly]

### PR DESCRIPTION
**Pull request by sahansk2**
### Resolves
*#209*

## Description
This PR applies the patch from audacity/audacity#900 while preserving original author and commit information using `git format-patch` and `git apply` (see [here](https://stackoverflow.com/a/3816292)). 

I'm not sure how to test this actually works (all I did was apply a patch), so I would appreciate guidance on that front.

Might be worth making a dedicated section in documentation for contributing guidelines on how to apply upstream patches from [audacity](https://github.com/audacity/audacity) , but that's a separate conversation.

- [X] I made sure the code compiles on my machine
- [X] I made sure there are no unnecessary changes in the code
- [X] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [X] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [X] I have confirmed that my code does not introduce intentional security flaws 

Maintainers have push access to this branch, so do what you want with this.

### CODE REVIEW

**Comment by sahansk2** [comment]
Also, I don't really know what

> code that is less bad than the code already there

means. Are there any additional changes that need to be made?

**Comment by mariaWitch** [comment]
This really just needs a sanity check to make sure that it's all good.
I didn't know if the code could be further optimized when I made the issue, but looking at it now, I think it should be fine.

Definitely needs further review though.

**Comment by Ckath** [comment]
it solves the very specific "cant import 8bit flac" issue by making it a valid 16bit flac on import. but I'm not sure if thats the correct way to go about it as a whole, still no real 'support' for 8bit flacs, not sure if that matters or not.

imo should just wait to see what upstream does with it, or if someone with the audio knowledge to fully see the implicatoin of doing this has any opinion about it.

**Comment by nek0bit** [comment]
It would probably be more effective to error out on an 8bit flac import instead of trying to treat it differently from what it really is.

**Comment by mariaWitch** [comment]
Specifically referencing the original bug report:
>It seems like 8-bit FLAC samples are imported with a wrong amplification factor
>to me it looks like the raw 8-bit values are interpreted as if they are from a
>16-bit sample, so only the low 8 of 16 bits are ever used.

**Comment by parkbanks** [comment]
Well with this method 0xff << 8 would give 0xff00, when I assume we want 0xffff. One method I've seen mentioned is buffer[chn][s] << 8 + buffer[chn][s]; though this might not be the accepted way in this scenario.

**Comment by mariaWitch** [comment]
I'll do a bit comparison between this and ffmpeg, and if it's the same, then this is probably good to go.

**Comment by Ckath** [comment]
after some discussion it seems 8bit flac isnt supported widely enough to be concerned about the whole 'but this isnt proper 8bit flac support' angle. and << 8 is proofing to be a valid method of converting from 8 bit flac to 16 bit flac.
so seems fine to merge unless theres strong opinions left about why it shouldnt be

**Pull request merged**
