### PR TITLE
Added License info to SNEEDME

### PR DESCRIPTION
**Pull request by LordRishav**

### CODE REVIEW

**Review by meguminloli — CHANGES_REQUESTED** [review]
Looks like Audacity is under GPL2. Please remove (and compatible licenses).

**Comment by LordRishav** [comment]
@meguminloli 
> [Code in the lib-src directory may be released under a different license (which is GPL-compatible).](https://github.com/audacity/audacity/blob/master/LICENSE.txt#L3)

 Some code is not licensed under the GPL, like those under [lib-src](https://github.com/Sneeds-Feed-and-Seed/sneedacity/tree/master/lib-src) directory, but is still under a GPL-compatible license.

**Comment by meguminloli** [comment]
I think that you should specify that. If I'm not mistaken, it's already stated in LICENSE

**Comment by LordRishav** [comment]
I think the best would be to just link to the License file for more information. Edited it to specify it.

**Pull request merged**
