### PR TITLE
Update tags and fix auto abuse

### PR DESCRIPTION
**Pull request by nek0bit**
The link referring to audacity forums is now invalid, so it's best removed, and we keep the original term for clarification purposes ("Offensive" might appear to be wrong to some people, the correct value should be returned here)

Resolves: Nothing

*(short description of the changes and the motivation to make the changes)*

- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I have confirmed that my code does not introduce intentional security flaws 

Needs to be compiled, but should compile just fine from my hard guesses. I sneed someone to test if possible, thanks

### CODE REVIEW

**Comment by formerlychuck** [comment]
works on my machine

**Comment by nek0bit** [comment]
Alright, thank you

**Comment by formerlychuck** [comment]
damn how long do these tests take

**Comment by formerlychuck** [comment]
ITODDLERS BTFO

**Comment by nek0bit** [comment]
> ITODDLERS BTFO

Haha speaking of, looking at getting builds to work on macOS, but will keep eye out on Conan removal

**Pull request merged**
