### PR TITLE
managed to build without conan

### PR DESCRIPTION
**Pull request by meguminloli**
Resolves: a lot of issues

- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I have confirmed that my code does not introduce intentional security flaws

### CODE REVIEW

**Comment by eylles** [comment]
BASED

**Comment by moxniso** [comment]
uh oh

**Comment by binex-dsk** [comment]
BASED

**Comment by mariaWitch** [comment]
As part of getting this to build on windows, we will need to remove and reintergrate one specific misbehaving  module. Not only does the current setup provide a useless/unnecessary level of abstraction, it provides no benefit to the build system as a whole a part from making the build process that much more difficult to decipher.

Once I have a working windows build I'll submit my changes to the PR.

**Comment by sin-ack** [comment]
This seems to be adding in multiple libraries directly into the repository, which is what we are trying to avoid (i.e. removing wxWidgets and using the upstream one). Perhaps this PR should wait until those dependencies can also be built without the entire source code of the libraries being inserted into the repository. Not only does vendoring force the repo to update dependencies manually, it also bloats the git objects.

**Comment by mariaWitch** [comment]
> This seems to be adding in multiple libraries (expat, lame, libmad etc.) directly into the repository, which is what we are trying to avoid (i.e. removing wxWidgets and using the upstream one). Perhaps this PR should wait until those dependencies can also be built without the entire source code of the libraries being inserted into the repository. Not only does vendoring force the repo to update dependencies manually, it also bloats the git objects.

Anything related to removing and extracting dependencies will be dealt with after we have a build system which isn't held together with popsicle sticks and glue.

Which is to say, it probably won't happen until we switch build systems.

**Comment by binex-dsk** [comment]
> it probably won't happen until we switch build systems.

speaking of which what build system should we use

i'm thinking just bootstrap/autoconfigure might work, or literally just plain Makefiles if severe pain is desirable

**Comment by Ckath** [comment]
for the ci issues I've done workarounds on https://github.com/Ckath/sneedacity/commits/rm_conan
forcably set shared library path to be the same as the regular one so files end up in the expected place, copy over expat and zlib which conan used to do (required by appimage), add a windows dependent check for utility_api. also some things suggested throughout the day by others.
havent really tested the apple builds, feel free to do so all artifacts are here: https://github.com/Ckath/sneedacity/actions/runs/1031793665

as of now the windows builds are still borked(do build but copy libs wrong) but the issue is known.
just leaving this here so others know where my patches are for this.

maybe also a good idea to just pr it to master when its all working? the idea was to throw things onto `conan_removal` here as they worked, but with this pr and me doing it elsewhere that kinda already stopped being the case. and it'll be pretty much usable anyway once the final things are ironed out.

can always just merge at least a buildable project without conan to master first and then later look at changing build systems(good luck), and using git submodules where libs are unpatched.

**Comment by mariaWitch** [comment]
Utility_Api can actually be removed if the changes from upstream regarding utility_lib are undone, and memoryX is reimported back into source. Check https://github.com/mariaWitch/sneedacity/commit/015cbef1568b8053927f6585d0bdf72bf2b86215  for the specific change to memoryX which had the issue with utility api

**Comment by Ckath** [comment]
ah nice, I never had an issue with utility_api being gone but I believe it was windows related. if that works for windows it can be left out.

**Comment by Ckath** [comment]
moved to master one at #218

**Pull request closed without merging**
