### PR TITLE
Add debug prints function

### PR DESCRIPTION
**Pull request by ChucksConsulting**
Add debug prints function

### CODE REVIEW

**Comment by moxniso** [comment]
You should really be using <cstdarg> to turn dprintf into a variadic function. Otherwise, you won't be able to use printf style formatting and actually output variable info.

**Comment by meguminloli** [comment]
> You should really be using cstdarg to turn dprintf into a variadic function. Otherwise, you won't be able to use printf style formatting and actually output variable info, and it'll only be functionally equivalent to puts despite your naming.

We can use variadic functions from C++, no need of cstdarg.

**Comment by meguminloli** [comment]
Replace `<iostream>` with <ostream>` and add variadic templates like
```
template <typename T, typename... Types>
void print(T var1, Types... var2)
{
    cout << var1 << endl ;
  
    print(var2...) ;
}
```
If I'm not mistaken, there is a `cooler` syntax, but I'm not sure if it's available in C++14.

**Comment by majestrate** [comment]
is there any reason to not pull in something like sdlog for a proper logging framework?

**Comment by ef3d0c3e** [comment]
> Replace `<iostream>` with `<ostream>` and add variadic templates like
> 
> ```
> template <typename T, typename... Types>
> void print(T var1, Types... var2)
> {
>     cout << var1 << endl ;
>   
>     print(var2...) ;
> }
> ```
> 
> If I'm not mistaken, there is a `cooler` syntax, but I'm not sure if it's available in C++14.

According to `CMakeLists.txt`, sneedacity is currently using c++17. Therefore, you should use fold expressions rather than recursion. Because template recursion has exponential complexity _(at compile time...)_, while fold expressions have linear complexity. Also, recursion depth is usualy limited by the compiler.
```c++
template <class... Ts>
void dprintf(Ts&&... ts)
{
    if (global_debug_prints_enabled)
    {
        ((std::cout << std::forward<Ts>(ts)), ...);
    }
}
```
I also added forwarding to forward arguments as lvalues or rvalues whenever one or the other is more appropriated.

**Pull request merged**
