### PR TITLE
New logo for Sneedacity !

### PR DESCRIPTION
**Pull request by MrBn100ful**
###  /!\ Vote for your favorite logo! https://www.strawpoll.me/45474940 /!\ 

Hi,
here the new logo:
Sneedacity_Logo_large
In action:
image
The source file : images/Sneedacity_Logo_large.svg

### CODE REVIEW

**Comment by ChucksConsulting** [comment]
This flat stuff looks more soulless than the one we have now.

**Comment by moxniso** [comment]
what if we got a skeuomorphic logo

**Comment by MrBn100ful** [comment]
> what if we got a skeuomorphic logo

I think we should keep the cartoon style, it fit with the Simpson theme.

**Comment by kakolisgay** [comment]
Design is a bit too flat imo

**Comment by ChucksConsulting** [comment]
> > what if we got a skeuomorphic logo
> 
> I think we should keep the cartoon style, it fit with the Simpson theme.

Analog video gave it a bit more texture than just perfectly plain colors everywhere.

**Comment by MrBn100ful** [comment]
Other versions:
image2
image3
image4
image5
image6
image7
image8
image9

**Comment by kakolisgay** [comment]
[124832774-b325e800-df6c-11eb-8c6f-d69e9d62c3e4](https://user-images.githubusercontent.com/9916074/124832774-b325e800-df6c-11eb-8c6f-d69e9d62c3e4.png) Looks pretty good, I'd be fine using that

**Comment by Ckath** [comment]
> [124832774-b325e800-df6c-11eb-8c6f-d69e9d62c3e4](https://user-images.githubusercontent.com/9916074/124832774-b325e800-df6c-11eb-8c6f-d69e9d62c3e4.png) Looks pretty good, I'd be fine using that

agreed, others said they preferred the colors though and no definite one has been picked. so some sort of vote?

**Comment by MrBn100ful** [comment]
an other idea 

logo2_org
logo2
on a taskbar:
Capture d’écran du 2021-07-08 00-11-39

**Comment by Ckath** [comment]
spoiled for choice, will have to work out some voting/suggestion

**Comment by EverlastingEndeavour** [comment]
A friendly suggestion: We can use every logo posted here for other Sneed's projects.

**Comment by sowa705** [comment]
> an other idea 
> 
> logo2_org
> logo2
> on a taskbar:
> Capture d’écran du 2021-07-08 00-11-39
> 

IMO this is the best, has that Windows XP era SOVL

**Comment by sonsofsneed3** [comment]
suggestion for the sneed logo icon
the sound waves look like sneed face :DDD
maybe something else can refine it

**Comment by sonsofsneed3** [comment]
suggestion for the sneed logo icon
the sound waves look like sneed face :DDD
maybe something else can refine it

**Comment by nulldg** [comment]
Just remember that the reason a new icon is needed is because the old Audacity logo is trademarked. Steer clear of trademark infringement (eg 'confusing similarity') or Muse would have a way to kick your ass.

Word Mark | AUDACITY
--- | ---
Goods and Services | IC 009. US 021 023 026 036 038. G & S: Downloadable computer software for creating, recording, editing, analyzing, and mixing digital audio and music. FIRST USE: 20010209. FIRST USE IN COMMERCE: 20010209
Mark Drawing Code | (3) DESIGN PLUS WORDS, LETTERS, AND/OR NUMBERS
Design Search Code | 01.15.24 - Sound waves, including designs depicting sound16.01.07 - Head phones ; Headphones ; Headsets ; Microphones
Serial Number | 90591173
Filing Date | March 19, 2021
Current Basis | 1A
Original Filing Basis | 1A
Owner | (APPLICANT) MuseCY SM Ltd. CORPORATION CYPRUS Spyrou Kyprianou, 84 4004 Limassol, Cyprus CYPRUS
Attorney of Record | Tony Berman
Prior Registrations | 2919070
Description of Mark | The color(s) blue, red, orange, and yellow is/are claimed as a feature of the mark. The mark consists of the word Audacity in rounded block letters in blue gradient to the right of a pair of headphones with a soundwave as displayed in a digital audio workstation (DAW) flowing between the ear cups of the headphones in which the headphones are in blue, and the soundwave is in red, orange, and yellow.
Type of Mark | TRADEMARK
Register | PRINCIPAL
Live/Dead Indicator | LIVE

**Comment by Ckath** [comment]
> Just remember that the reason a new icon is needed is because the old Audacity logo is trademarked. Steer clear of trademark infringement (eg 'confusing similarity') or Muse would have a way to kick your ass.
someone else mentioned the logos were still under CC, which was also my undertanding. but at any rate it should be fine with the more artistic ones. if it comes to the worst case something completely different can always be made

**Comment by weevilgit** [comment]
Hey, here are the images. I'm still working on the ones with the paintbrush, though that's for the other project, so irrelevant here.

I'm also trying to make a variation of the simpsons font that wouldn't be copyrighted so we can have a Sneedacity text alongside the logo.

Sneedacity no body with headphones
Sneedacity no body
Sneedacity No Goatee
Sneedacity No Headphones
Sneedacity

**Comment by MrBn100ful** [comment]
@nulldg so my logo is a no go with the current design right ?

**Comment by MrBn100ful** [comment]
Capture
this should be trademark free

**Comment by sowa705** [comment]
I'd just like to say that
124852785-3817fe00-df7b-11eb-865b-f2e5b810a90f
looks absolutely the best of all other logos. Makes it obvious its audio related, has SNEED and has soul.

**Comment by weevilgit** [comment]
> @weevilgit could you upload the svg ?

Hey, it's actually a 2000x2000 px raster. I could vectorize it if rasters aren't the standard.

**Comment by NO-ob** [comment]
sneedacity2
sneedacity

**Comment by mariaWitch** [comment]
> Just remember that the reason a new icon is needed is because the old Audacity logo is trademarked. Steer clear of trademark infringement (eg 'confusing similarity') or Muse would have a way to kick your ass.
> 
> Word Mark	AUDACITY
> Goods and Services	IC 009. US 021 023 026 036 038. G & S: Downloadable computer software for creating, recording, editing, analyzing, and mixing digital audio and music. FIRST USE: 20010209. FIRST USE IN COMMERCE: 20010209
> Mark Drawing Code	(3) DESIGN PLUS WORDS, LETTERS, AND/OR NUMBERS
> Design Search Code	01.15.24 - Sound waves, including designs depicting sound16.01.07 - Head phones ; Headphones ; Headsets ; Microphones
> Serial Number	90591173
> Filing Date	March 19, 2021
> Current Basis	1A
> Original Filing Basis	1A
> Owner	(APPLICANT) MuseCY SM Ltd. CORPORATION CYPRUS Spyrou Kyprianou, 84 4004 Limassol, Cyprus CYPRUS
> Attorney of Record	Tony Berman
> Prior Registrations	2919070
> Description of Mark	The color(s) blue, red, orange, and yellow is/are claimed as a feature of the mark. The mark consists of the word Audacity in rounded block letters in blue gradient to the right of a pair of headphones with a soundwave as displayed in a digital audio workstation (DAW) flowing between the ear cups of the headphones in which the headphones are in blue, and the soundwave is in red, orange, and yellow.
> Type of Mark	TRADEMARK
> Register	PRINCIPAL
> Live/Dead Indicator	LIVE

The audacity website states that all text and images are licensed under CC3.
Images like their logo would be included in that, but basically what you are saying is that MUSE is also violating CC now?

**Comment by ChucksConsulting** [comment]
> > @weevilgit could you upload the svg ?
> 
> Hey, it's actually a 2000x2000 px raster. I could vectorize it if rasters aren't the standard.

Then add the source file with the different layers.

**Comment by kostas-from-cyber-space** [comment]
@mariaWitch You can use CC license for a logo or trademark but it isn't recommended (https://creativecommons.org/faq/#could-i-use-a-cc-license-to-share-my-logo-or-trademark). In Audacity's case they should've made clear that their logo is trademarked on the copyright page (https://www.audacityteam.org/copyright/) and different permissions apply (https://creativecommons.org/faq/#can-i-offer-material-under-a-cc-license-that-has-my-trademark-on-it-without-also-licensing-or-affecting-rights-in-the-trademark).

**Comment by formerlychuck** [comment]
I wonder if @NO-ob 's logo violates some kind of IP law, otherwise that would be my pick

**Comment by binex-dsk** [comment]
>he cares about laws

**Comment by weevilgit** [comment]
> Then add the source file with the different layers.

Any format you suggest that respects my privacy? I don't trust .psd files in regards to metadata. Specifically, the following tags:

`<xmpMM:InstanceID>`

`<xmpMM:DocumentID>`

`<xmpMM:OriginalDocumentID>`

There are a lot of mentally ill OSINT larpers observing us right now because of the two fake news that just got passed around about 4chan stabbing a man with a butterfly knife, and that other emugen guy killing himself. I really don't want some terminally online retard who's saving the world fighting invisible nazis trying to bother me.

**Comment by kartur** [comment]
> Hey, here are the images. I'm still working on the ones with the paintbrush, though that's for the other project, so irrelevant here.
> 
> I'm also trying to make a variation of the simpsons font that wouldn't be copyrighted so we can have a Sneedacity text alongside the logo.
> 
> Sneedacity no body with headphones
> Sneedacity no body
> Sneedacity No Goatee
> Sneedacity No Headphones
> Sneedacity
> 
> If you guys want any variations of those just ping me or whatever on github (not sure how it works, I don't really use it.)

Honestly, I don't really like the shading. Style reminds me of a specific style of emojis (not the good ones). Could you perhaps try using solid colors? And also colors that look a little more like the original ones?

Also in my opinion the icon is too complex/detailed. It doesn't really look like much if you place it on the desktop for example.

And I also I agree with the person who said that the focus on audio is not very outstanding.

Sorry if this sounds discouraging, just my two cents.


Overall I like MrBn100ful icons best, especially the second . They are simple, look good in all sizes, have character and the sneed cap just looks good in it.

Maybe let's wait for some more ideas and then start voting. :)

image

**Comment by Ckath** [comment]
> Overall I like MrBn100ful icons best, especially the second . They are simple, look good in all sizes, have character and the sneed cap just looks good in it.
> 
> Maybe let's wait for some more ideas and then start voting. :)
> 
> image

from a discusson earlier in the matrix it was more or less agreed 1 was the pick. I also recall people liking it in the thread. and works well with adjusting for simp and future projects.

think its a good plan to go with that before we get 100 logo suggestions. unless anyone really disagrees that one

**Comment by mininmobile** [comment]
whe
image
when the

(and that concludes my case on why 1 is the obvious choice)

**Comment by sowa705** [comment]
I think this is ready to close, no one objected to it.

**Comment by weevilgit** [comment]
> > Then add the source file with the different layers.
> 
> Any format you suggest that respects my privacy? I don't trust .psd files in regards to metadata. Specifically, the following tags:
> 
> `<xmpMM:InstanceID>`
> 
> `<xmpMM:DocumentID>`
> 
> `<xmpMM:OriginalDocumentID>`

Does anyone have a suggestion about this? All the rights go to the project, and I want to send you guys the editable files. All I ask is for a way of scrubbing metadata, or another format to send it that doesn't leak personal info whatsoever.

**Comment by SoulRepo** [comment]
> 
> 
> whe
> image
> when the
> 
> (and that concludes my case on why 1 is the obvious choice)

no

**Comment by MrBn100ful** [comment]
I have made a poll: https://www.strawpoll.me/45474940
logos in order:
image
image
image
image
image

**Comment by MrBn100ful** [comment]
I have made a poll: https://www.strawpoll.me/45474940
logos in order:
image
image
image
image
image

**Comment by gamelone** [comment]
124965277-d78bce00-e019-11eb-8908-01f6cfe17b09
This is Chuck, not Sneed

**Comment by nobuyukinyuu** [comment]
image
(This, but slightly less crappy)

**Comment by eylles** [comment]
kek, we need a better poll tbh.
how awful would it be to use google forms?

**Comment by Ckath** [comment]
> kek, we need a better poll tbh.
> how awful would it be to use google forms?

\>voting requires proprietary form
\>tfw the botnet doesnt let me have a vote on the logo

**Comment by eylles** [comment]
kek, k we vote in matrix

**Comment by Ckath** [comment]
logos were already discussed in matrix scroll up

**Comment by TheRealPSV** [comment]
Weevilgit's logo is a great blend of nostalgic and aesthetic, I like it.

> Sneedacity


Also wouldn't the below logo get the project in trouble anyway since Chuck & Sneed's images would be copyrighted?

> 124965277-d78bce00-e019-11eb-8908-01f6cfe17b09

**Comment by Ckath** [comment]
> Weevilgit's logo is a great blend of nostalgic and aesthetic, I like it.

so do many people I wish it'd be pushed through already

> Also wouldn't the below logo get the project in trouble anyway since Chuck & Sneed's images would be copyrighted?

its at least far more likely to, and theres plenty alternative logos to pick from now that avoid it from happening

**Comment by MrBn100ful** [comment]
the winner logo in action:
image

**Pull request merged**
