### PR TITLE
change .srcinfo and pkgbuild

### PR DESCRIPTION
**Pull request by T0x1cL**
just changed the group to "sneed-suite" instead of "pro-audio", not really an issue i dunno, just to make management of sneed packages easier

- [x] I have confirmed that my code does not introduce intentional security flaws

### CODE REVIEW

**Comment by Ckath** [comment]
ah yeah fair catch, missed that in the quick s/audacity/sneedacity creation of it

**Comment by T0x1cL** [comment]
imo the description shouldn't only be "Audacity fork without any telemetry (git-version)", but that can probably come after the sneedacity community decides on one.

~~I'd like if sneed is somewhere in the description.~~

**Comment by Ckath** [comment]
that was just to to pull it similar to how other audacity forks were listed in the aur https://aur.archlinux.org/packages/?K=audacity, but more sneed can always be added

**Comment by meguminloli** [comment]
Add as much sneed as you can. AUR mods took down the package for no reason.

**Pull request merged**
