### PR TITLE
Bumped ffmpeg to 4.4

### PR DESCRIPTION
**Pull request by HamletDuFromage**
Probably a good idea to not use a 7 years old version of the library

- [x] I made sure the code compiles on my machine
- [ ] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I have confirmed that my code does not introduce intentional security flaws

### CODE REVIEW

**Comment by Ckath** [comment]
all the builds are dying, but the idea is good

**Comment by HamletDuFromage** [comment]
Ah that's odd, literally werks on my machine

**Comment by Ckath** [comment]
the actions are mildly retarded and use some different build options and libs, maybe the windows ones will go through they're still going at it

**Comment by nulldg** [comment]
The windows one exploded too. Given the nature of the pull request, I'm unsurprised the actions broke here.
https://github.com/Sneeds-Feed-and-Seed/sneedacity/pull/135/checks?check_run_id=3022969681#step:7:779
```
D:\a\sneedacity\sneedacity\lib-src\ffmpeg\libavcodec/avcodec.h(39,10): fatal error C1083: Cannot open include file: 'libavutil/hwcontext.h': No such file or directory [D:\a\sneedacity\sneedacity\build\src\Sneedacity.vcxproj]
```

**Comment by 0kalekale** [comment]
bumping ffmpeg will break everything. there are major api changes. not worth it.

**Pull request closed without merging**
