### PR TITLE
Final wording change

### PR DESCRIPTION
**Pull request by mariaWitch**
Glowies BTFO.

### CODE REVIEW

**Comment by mariaWitch** [comment]
By popular request, fancy german cars is another option

**Comment by ChucksConsulting** [comment]
The final wording will be decided in a poll which is in the process of being set up. Please contribute all the suggestions before the poll URL is announced.

**Comment by ChucksConsulting** [comment]
Please get all your suggestions in before the poll is created
Current suggestions are:

(Cuck Licenses BTFO)
(Permissive Licenses BTFO)
(Chuck Licenses BTFO)
(CORNVTVS Licenses BTFO)
(City Slicker Licenses BTFO)
(Remove the statement inside the parentheses entirely)
Other

**Comment by ChucksConsulting** [comment]
POLL IS GOING LIVE
https://www.strawpoll.me/45479732

**Pull request merged**
